### ISSUE TITLE
`group` class?

### ISSUE THREAD

**Issue by bencevans** [microsoft/CameraTraps#146]
Hi

Please could you clarify as to what the `group` class is supposed to represent? Group of animals, group of people, vehicles...?

Thanks

Ben

**Comment by yangsiyu007** [comment]
Hi @bencevans , `group` is a class only present in annotations we receive from our annotators. It denotes a group of animal with more than about 20 individuals, so that the annotators don't have to label each with a bounding box. Images with `group` are not used when training the animal/human/vehicle detection model (MegaDetector).

**Comment by bencevans** [comment]
Thanks @yangsiyu007! We saw it pop up in the `detection_categories` and was wondering. There are some detections but all have a `0.0` confidence.

![image](https://user-images.githubusercontent.com/638535/78176377-4a3fee00-7454-11ea-94b2-118a3d8b8d84.png)
