### ISSUE TITLE
multi-GPU inference

### ISSUE THREAD

**Issue by matobler** [microsoft/CameraTraps#160]
Is there an easy way to use multiple GPUs for inference for the MegaDetector? That could speed things up quite a bit for large datasets.

**Comment by yangsiyu007** [comment]
I don't know of an "easy" way to use multiple GPUs on one machine, except by running the inference script in separate processes, where you manually set the `CUDA_VISIBLE_DEVICES ` environment variable to be the GPU you'd like that script to use, and modify the script to score a subset of the images (shard the images somehow manually)...

**Comment by agentmorris** [comment]
This is a good idea, and something I've been meaning to do but haven't quite gotten to yet... I think there are a couple ways that one could do this with `run_tf_detector_batch.py`:

1. Write a new script, in Python or in bash, that separates the images in advance into two piles, and invokes run_tf_detector batch twice, with `CUDA_VISIBLE_DEVICES` set to 0 for one process and 1 for the other.  This should be as straightforward as just setting `CUDA_VISIBLE_DEVICES` in the new script before invoking each child process (the child process will inherit the environment variable as it was set at the time you invoked the child process).  If I were doing this, I would do it in Python, and I would also modify `run_tf_detector_batch.py` to take a list of files as input (rather than a folder), which would be a small change that would make this a little more elegant.  This script would also have to merge the outputs from the two child processes.  A little inelegant, but requires only surface-level interactions with existing code, and possibly minor modifications to `run_tf_detector_batch.py`.

2. Conveniently, we just introduced some basic multiprocessing functionality to `run_tf_detector_batch.py` intended for CPUs, which splits images into batches and creates multiple processes.   Around line 135, we explicitly check whether you're trying to do multiprocessing with GPUs, so that would need to go, and then we use multiprocessing.pool to fire up processes that run the process_images() function.  It should be relatively straightforward to pass an index to those processes, and either set `CUDA_VISIBLE_DEVICES` or use the `with tf.device('/gpu:0')` syntax (e.g. [this post](https://jhui.github.io/2017/03/07/TensorFlow-GPU/)). to specify a GPU for each process based on its index.  If all goes well, this is also just a couple lines of modification, though the work is in what happens if all doesn't go well. :)

My recommendation would be (2); otherwise you get into the complicated business of passing a lot of command-line arguments through to `run_tf_detector_batch.py`.

In either case, it would be rather complicated to implement the functionality that exists in `run_tf_detector_batch.py` to resume from a checkpoint, but this may not be necessary.  We already punt on this for CPU-based multiprocessing.

We may get to this soon, but @matobler , if you're interested in taking a shot at it, we'd welcome your feedback and/or contribution!

Thanks.

-Dan

**Comment by matobler** [comment]
Hi Dan, 

Sorry for the late response. I did start looking into the code (and realized that you run one image at a time and not batches), but to be honest my python skills are too rudimentary to implement the parallel processing myself. For now, I did use the `CUDA_VISIBLE_DEVICES` to run two batches at the same time on the two GPUs. It would be nice (and easy) to have a command line argument for which GPU to use.

I am actually currently working on running the MD directly in R. The basic stuff is working but it's a bit slower (some overhead of passing data between R and Python in the background I suppose). I might try some of the parallel processing there, since I am very familiar with that in R.

Thanks,

Mathias

**Comment by agentmorris** [comment]
Glad we got you to an acceptable workaround, sorry we haven't had the bandwidth to add either parallelization or GPU specification directly.

Please do let us know if you get an R example running, we'd love to have that here on the repo to point other R users to!

**Comment by agentmorris** [comment]
Minor updates here, and closing the issue...

*Minor updates*

Firstly, though it's not quite as elegant as integrating everything directly into run_tf_detector_batch.py, we have been more extensively testing the following approach, which is as good as having a command-line argument (and less work to implement):

`CUDA_VISIBLE_DEVICES=0 python run_tf_detector_batch.py [all your arguments]
`

More specifically, when we run a large batch of images, we don't actually use run_tf_detector_batch.py directly, we call it as part of a larger process that includes enumerating images, optionally splitting them into multiple evenly-sized tasks, running the model (with run_tf_detector_bach.py), merging the results, and doing a variety of optional postprocessing steps, including generating a nice report that we send to users, sometimes adjusting the output .json file to be compatible with a user's workflow, etc.

[manage_local_batch.py](https://github.com/microsoft/CameraTraps/blob/master/api/batch_processing/data_preparation/manage_local_batch.py) is the "script" we use to manage this process, though "script" is in quotes because this is more like a notebook that's meant to be copied and run interactively (#%% is a cell delimiter that's supported by VS Code and Spyder).

You'll get the idea even if you haven't worked with cell-delimited Python scripts before.  The cell called "generate commands" writes out .sh files (typically one per GPU) with CUDA_VISIBLE_DEVICES specified appropriately, and it's been working great.

*Closing the issue*

Closing the issue because we are getting closer to releasing MDv5, which will use PyTorch rather than TensorFlow, so it no longer makes sense to make substantial architectural changes to run_tf_detector_batch.py.

--

Hope your R work is going well, let us know if you have a stable R wrapper for MegaDetector.  Thanks!
