### ISSUE TITLE
Tutorial is out of date

### ISSUE THREAD

**Issue by forcecore** [microsoft/CameraTraps#259]
From the main README.md,  in section classification (https://github.com/microsoft/CameraTraps#classification),
it states "here's a tutorial on training your own classifier using our detector and our training pipeline." and points to the archived TUTORIAL.md (https://github.com/microsoft/CameraTraps/blob/master/archive/classification_marcel/TUTORIAL.md).

However, the tutorial seems to be far out of sync with the readme in https://github.com/microsoft/CameraTraps/blob/master/classification/README.md.

I am still unsure how to run the training with my dataset with the current master branch.

**Comment by agentmorris** [comment]
Great question, and sorry for the confusion.  I've updated the text on the main page to clarify what I'm about to say here...

We don't have a ready-to-go pipeline for classifier training, as the vast majority of our work is focused on MegaDetector.  There are two frameworks for training classifiers in the "classification" folder, both likely-less-than-helpful-for-you for different reasons:

1) The main classification framework (described in the [main README](https://github.com/microsoft/CameraTraps/tree/master/classification)) is up to date, but depends on an internal database of labeled images (referred to in the documentation as "MegaDB").
2) The [tutorial](https://github.com/microsoft/CameraTraps/blob/master/archive/classification_marcel/TUTORIAL.md) you referred to is completely standalone, but uses what are now obsolete dependencies.

If you are looking to train species classifiers, here are a few general paths you might go down, depending on your scenario:

* If you want to use MegaDetector to generate crops, and train your classifier just on cropped animals, you can...
    1. Run MegaDetector, use [crop_detections.py](https://github.com/microsoft/CameraTraps/blob/master/classification/crop_detections.py) to extract crops as individual images, then use whatever your favorite ML framework/tutorial is to train a classifier.
    2. Use our [current classification framework](https://github.com/microsoft/CameraTraps/tree/master/classification), but modify it to read labels from somewhere other than our internal database (which would still allow you to use, e.g., our inference and scoring tools).  We are unlikely to be able to take this on as a project, but would welcome contributions that decouple our classification framework from MegaDB.
    3. Modernize the older [tutorial for standalone classifier training](https://github.com/microsoft/CameraTraps/blob/master/archive/classification_marcel/TUTORIAL.md).  Again, we would welcome this as a contribution to the repo.
* If you want to train a classifier on <i>whole images</i> (rather than crops), you probably won't derive much benefit from the tools we have here.

Whichever way you proceed, one thing you may find useful from our repo is the [MegaDetector batch API output format](https://github.com/microsoft/CameraTraps/tree/master/api/batch_processing#batch-processing-api-output-format), which has a defined schema for classification results.  Some OSS camera trap image review tools - for example, [Timelapse](http://saul.cpsc.ucalgary.ca/timelapse/) - know how to read this format; this is how users interact with results of the classifiers we train.

Hope that helps, and thanks for reminder to clarify this outdated information on the main page.

Thanks!

-Dan

**Comment by forcecore** [comment]
Thank you for your reply.

I'm working on a "hello world" project for other researchers who aren't very familiar with Deep Learning. I guess contributing to this repository is beyond the scope of my tutorial.
