### ISSUE TITLE
cannot import name 'TFDetector' from 'detection.run_detector

### ISSUE THREAD

**Issue by totoadel** [microsoft/CameraTraps#281]
using colab 
```
Traceback (most recent call last):
  File "run_tf_detector_batch.py", line 66, in <module>
    from detection.run_detector import ImagePathUtils, TFDetector
ImportError: cannot import name 'TFDetector' from 'detection.run_detector' (/content/CameraTraps/detection/run_detector.py)
```

**Comment by agentmorris** [comment]
Thanks for catching this; we made some updates to our repo recently that required some changes to the Colab.  I've posted a [new version of the Colab](https://github.com/microsoft/CameraTraps/blob/main/detection/megadetector_colab.ipynb); try that?  Closing because I'm 99% sure this will fix your issue, and I just verified it from a clean Colab session.
