### ISSUE TITLE
eliminating repeated detection

### ISSUE THREAD

**Issue by barlavi1** [microsoft/CameraTraps#293]
Hi Dan,
thank you for your quick reply! (Issue #290 )

after running the pipeline:
* find_repeat_detections.py
* manually removing false posittives
* remove_repeat_detections.py
I end up with a json file.
when running this json file in the script postprocess_batch_results.py, I get the following error:
File "load_api_results.py", line 93, in load_api_results
assert s in detection_results, 'Missing field {} in detection results'.format(s)
AssertionError: Missing field info in detection results

Looking at the json file, it doesn't have the same fields as in the output json file of the run_detector_batch.py.

Is there a way use the postprocess_batch_results.py on the json file of the repeat detections?

Thanks

**Comment by agentmorris** [comment]
Sorry you're having trouble with the RDE process.

Firstly, clarifying that when you say "manually removing false positives", you should be removing detections on *actual objects*.  I.e., from MegaDetector's perspective, you should be removing *true positives*, not *false positives*.  That may be what you meant, but this is important, so clarifying.  What's left in the directory when you're done with the manual step should be images with boxes on junk (rocks, sticks, etc.).  The [README on RDE](https://github.com/microsoft/CameraTraps/tree/main/api/batch_processing/postprocessing/repeat_detection_elimination#cleaning-up-the-suspicious-detections-that-were-in-fact-real-objects) has specific examples of what you should/shouldn't be deleting.

Regarding the .json file... are you sure you are using the file you specified as the output file in remove_repeat_detections(), rather than the "detectionIndex.json" file that is produced by find_repeat_detections()?  detectionIndex.json is just an intermediate file that's used to communicate the list of detections between find_repeat_detections() and remove_repeat_detections(). 

If you are in fact using the output from from remove_repeat_detections(), can you:

1. Confirm that remove_repeat_detections() runs without error, and send the command-line output?
2. Share the resulting .json file, either here or via email to cameratraps@lila.science?

Thanks.

-Dan

**Comment by agentmorris** [comment]
Great!  Glad it worked.  Closing this issue.
