### ISSUE TITLE
Are the MDv5 pt files "normal" YOLOv5 model files?

### ISSUE THREAD

**Issue by abfleishman** [microsoft/CameraTraps#294]
Are the MDv5 pt files "normal" YOLOv5/PyTorch model files? Aka can I use my existing scripts for running YOLOv5 models to run MDv5? or is there something custom about the pt files that I need to be aware of?

**Comment by agentmorris** [comment]
Yes, they should be like any other Yolov5 model.  We increment the class values by 1 in our inference scripts to match the convention we used for MDv4, but you would figure that out pretty quickly, and that's just a question of output semantics, not a question of the normal-ness of the model files.

All other things being equal, we would recommend using our script (run_detector_batch.py), because you'll get data in a format that's consistent with all of our other tools (plus tools like Timelapse), but that's a convenience, not a requirement.

Let us know if you discover otherwise!
