### ISSUE TITLE
Matplotlib in postprocess_batch_results.py

### ISSUE THREAD

**Issue by BrentPease1** [microsoft/CameraTraps#319]
Within the api\batch_processing\postprocessing\postprocess_batch_results.py script, a call to import matplotlib was commented out and now an error occurs on Line 46.

"Traceback (most recent call last):
  File "c:\git\cameratraps\api\batch_processing\postprocessing\postprocess_batch_results.py", line 46, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'"

**Comment by agentmorris** [comment]
Closed by the OP; for posterity, this is likely an issue with matplotlib not being available in the current Python environment, rather than an issue with the commented-out line the OP referred to.  matplotlib is included in our Conda environment files, but if you're rolling your own environment, "pip install matplotlib" will likely fix this issue.

Glad the OP (presumably) found a solution!
