### ISSUE TITLE
Is there a reason the non-headless version of opencv is used? 

### ISSUE THREAD

**Issue by reinhrst** [microsoft/CameraTraps#332]
I was just trying to get CameraTraps working on a headless linux RTX3080 computer (in docker). The `environment-detector.yml` file installs `opencv`, which will only run if a lot of (UI) dependencies are installed.

I replaced it in my install with `opencv-python-headless`:

```diff
diff --git a/environment-detector.yml b/environment-detector.yml
index 90d6178..a55fec8 100644
--- a/environment-detector.yml
+++ b/environment-detector.yml
@@ -3,6 +3,7 @@ name: cameratraps-detector
 channels:
   - conda-forge
   - pytorch
+  - fastai

 dependencies:
   - python=3.8
@@ -17,7 +18,7 @@ dependencies:
   - matplotlib
   - nb_conda_kernels
   - ipykernel
-  - opencv
+  - opencv-python-headless
   - requests

   # for running MegaDetector v4
```

Happy to submit a PR, but would like to check if there is a use case where the non-headless part is needed.

**Comment by agentmorris** [comment]
Thanks for the suggestion!

Honestly the main reason is that this is the first I've ever heard of opencv-python-headless.  It seems like a good idea, but two other concerns came up, maybe you can talk me out of them?

1. The main concern is that we have an increasing set of users who are using [process_video.py](https://github.com/microsoft/CameraTraps/blob/main/detection/process_video.py) and its friends, which depends on OpenCV for video encoding/decoding, and a very cursory search on opencv-python-headless suggests that it *might* change the set of video tools that are installed.

2. I'm around 95% sure that nothing bad will come of adding another channel to the conda environment file, but this is one of those things where it worries me that I can't test this on all possible configurations.

(1) is the  larger concern here.  Do you know anything about the relationship between opencv-python-headless and the installation of ffmpeg and related utilities?

Also is the main benefit about installation time, or did you experience other issues related to the non-headless OpenCV install?  If it's mostly about installation time, I'm slightly inclined not to rock the boat, since I think installing PyTorch is the vast majority of the installation time anyway.

**Comment by reinhrst** [comment]
I can address the last question the easiest: I got an error when trying to run the system in a docker container:

```
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
```

[It seems](https://stackoverflow.com/questions/55313610/importerror-libgl-so-1-cannot-open-shared-object-file-no-such-file-or-directo) that this can be resolved either by installing some things (which resulted in my case in a huge dependency-tree being pulled in), or alternatively use the headless version of opencv (in which case it all installs just fine in Docker).

I didn't consider which video codecs get installed -- I can actually imagine that installing the huge dependency-tree may pull in some additional codecs. Makes sense to be hesitant to change this if all it does is fix an issue that can easily be fixed some other way (by `apt-get install ....`)

**Comment by agentmorris** [comment]
Thanks... since we haven't heard of that issue before (including in various Docker environments), I think we'll play this one on the safe side and leave it as-is.  Thanks for the suggestion, though!  Hope everything else is working out w/MegaDetector for you, glad you found a way through this issue.
