### ISSUE TITLE
Capture image date/time (Possible enhancmenet)

### ISSUE THREAD

**Issue by aweaver1fandm** [microsoft/CameraTraps#337]
I was just wondering if there's any kind of flag when running the batch detector to include the image date and time (the date/time the image was taken) as part of the JSON output?  I looked quickly and didn't see anything that seemed to do that.

If something like that does not exist, then I would like to ask it be considered as an enhancement also making sure that date/time information is copied as part of convert_output_format.py.  Our researcher here, and I could imagine other researchers, finds this information very helpful as they do various analyses as part of their post-processing procedures.

**Comment by agentmorris** [comment]
We don't do this right now, but you're right that since we have to read the images anyway, it wouldn't really slow processing down significantly (I think?), and I can see a number of scenarios where it would be convenient.

One of the reasons we haven't done this is that most MegaDetector users read their MD results into [Timelapse](https://saul.cpsc.ucalgary.ca/timelapse/), which already reads date/time information from images.  If you are planning to use Timelapse, I think you don't need anything extra from the MegaDetector inference scripts.

FYI, we have a separate script ([read_exif.py](https://github.com/microsoft/CameraTraps/blob/main/data_management/read_exif.py
)) to fetch all metadata for all images in a folder; I typically combine this after the fact with MegaDetector results.  

So you have a couple of paths by which you may not actually need new functionality, but I'll leave this open for now, in fact I'll tag this as "good first issue", this is relatively self-contained.
