### ISSUE TITLE
Error installing torch==1.10.1 in Colab notebook

### ISSUE THREAD

**Issue by ronbitonn** [microsoft/CameraTraps#356]
I am encountering an error while trying to install torch==1.10.1 in a Colab notebook. The specific command I am using is !pip install torch==1.10.1 torchvision==0.11.2. However, I am getting the following error message:

yaml
Copy code
ERROR: Could not find a version that satisfies the requirement torch==1.10.1 (from versions: 1.11.0, 1.12.0, 1.12.1, 1.13.0, 1.13.1, 2.0.0, 2.0.1)
ERROR: No matching distribution found for torch==1.10.1
I need assistance in resolving this issue so that I can successfully install torch==1.10.1 in my Colab notebook.

Steps to reproduce the issue:

Create a new Colab notebook.
Execute the command !pip install torch==1.10.1 torchvision==0.11.2.
Expected result:
The command should successfully install torch==1.10.1 and torchvision==0.11.2 without any errors.

Actual result:
The installation fails with the error message mentioned above.

Additional information:
I have already tried specifying other versions of the torch, but the error persists.
The Colab notebook environment has internet access.
Any assistance or insights to resolve this issue would be greatly appreciated. Thank you!

**Comment by Yuri-Njathi** [comment]
#having a similar problem

`The conflict is caused by:`
`    pytorchwildlife 1.0.2.13 depends on torch==1.10.1`
`    pytorchwildlife 1.0.2.12 depends on torch==1.10.1`
`    pytorchwildlife 1.0.2.11 depends on torch==1.10.1`
`    pytorchwildlife 1.0.2.10 depends on torch==1.10.1`
`    pytorchwildlife 1.0.2.9.1 depends on torch==1.10.1`
`    pytorchwildlife 1.0.2.9 depends on torch==1.10.1`
`    pytorchwildlife 1.0.2.8 depends on torch==1.10.1`
`    pytorchwildlife 1.0.2.5 depends on torch==1.10.1`
`    pytorchwildlife 1.0.2.4 depends on torch==1.10.1`
`    pytorchwildlife 1.0.2.3 depends on torch==1.10.1`
`    pytorchwildlife 1.0.2.2 depends on torch==1.10.1`
`    pytorchwildlife 1.0.1.1 depends on torch==1.10.1`
`    pytorchwildlife 1.0.1 depends on torch==1.10.1`
`    pytorchwildlife 1.0.0 depends on torch==1.10.1`
`    pytorchwildlife 0.0.1.1.2 depends on torch==1.10.1`
`    pytorchwildlife 0.0.1.1.1 depends on torch==1.10.1`
`    pytorchwildlife 0.0.1 depends on torch==1.10.1`
`    pytorchwildlife 0.0.0 depends on torch==1.10.1`

`To fix this you could try to:`
`1. loosen the range of package versions you've specified`
`2. remove package versions to allow pip attempt to solve the dependency conflict`
