### ISSUE TITLE
PytorchStreamReader failed reading zip archive

### ISSUE THREAD

**Issue by yodaka0** [microsoft/CameraTraps#392]
Excuse me.
I run MegaDetector on laptop pc.
But below error occurs.
PytorchStreamReader failed reading zip archive: failed finding central directory
OS : Windows 10 Home
Processor: AMD Ryzen 7 3700U with Radeon Vega Mobile Gfx     2.30 GHz

**Comment by zhmiao** [comment]
Hello @yodaka0, thank you so much for reporting this! Could you please share more details on how did you get the error? If you could make a small snippet that can reproduce the error, it would be the best! Also, could you send us the full error message as well? Thanks again!

**Comment by yodaka0** [comment]
Thanks your thinking and reply.

Using threads for queue
1702183773.9032795
Loaded model (before queueing) in 0 seconds
Image C:\Users\shoun\Documents\herp\Pf_2021-04-10_00195613.JPG cannot be processed. Exception: PytorchStreamReader failed reading zip archive: failed finding central directory

 
I tried load MegaDetector directly from row program, but failed.
I guess because processor is not i core.
Thanks again.

**Comment by zhmiao** [comment]
Hello @yodaka0 , thanks for sharing the error message. I think this might be caused by corrupted or unfinished downloads according to this issue: https://github.com/pytorch/pytorch/issues/31620 

There might be a possibility that the weights are not downloaded properly but I am not 100% sure. Did this error happen when you run `detection_model = pw_detection.MegaDetectorV5()` ?

**Comment by yodaka0** [comment]
Thanks your replay.
Because it’s not own pc, now I can’t check this, but I may be so.

**Comment by zhmiao** [comment]
Hello @yodaka0, we want to check in if there are any updates on this issue?
