### ISSUE TITLE
MegaDetectorV6 release

### ISSUE THREAD

**Issue by Gasp34** [microsoft/CameraTraps#478]
### Search before asking

- [X] I have searched the Pytorch-Wildlife [issues](https://github.com/microsoft/CameraTraps/issues) and found no similar bug report.

### Question

Hello, do you have an approximate release date for MegaDetectorV6?

**Comment by zhmiao** [comment]
Hello @Gasp34, thank you very much for asking! Currently, we are still tuning MegaDetectorV6 ensuring its performance and compatibility. Our current plan for the initial release is some time in the next two to three weeks, mid-May at latest. If we end up being later than mid-May, we will make an announcement for it. Please keep an eye on our repo or join our Discord for update news! Thank you again!

**Comment by Gasp34** [comment]
Thank you very much for your reply @zhmiao! I'm really looking forward to testing MegaDetector with a lighter model size :)

**Comment by zhmiao** [comment]
Hello @Gasp34, we are very sorry for the delay, but we have some news for MegaDetectorV6 and announced it in our readme. We are starting a beta testing for the model and if you are interested in participating, please let us know! Thanks!

**Comment by Gasp34** [comment]
Hello @zhmiao, no worries about the delay, I would be glad to help with beta testing! I do not have access to bounding boxes but what I usually do is that I evaluate the pipeline detector+classifier and see if there is an improvement with the new detector.

**Comment by zhmiao** [comment]
Hello @Gasp34 , we have finalized the code for MegaDetectorV6 beta testing. To access the code, you will need to switch to the "MDv6_beta" branch. You can either "pip install -e ." to install the beta package from the source code or directly use the source code. Please dm me or find me on discord for MegaDetectorV6 weights.
 
Currently we do not have direct url loading for limited access. To test the model, you can use the demo script in this branch "demo/image_demo.py" and change the path to your downloaded weights in this line: https://github.com/microsoft/CameraTraps/blob/4392cae5088cc98bbd40b2209bcdda1f6f7be01b/demo/image_demo.py#L24
 
You will see that now, the use of MegaDetector is further simplified. You only need to give the detection function a path to your image or data folders, rather than define datasets and dataloaders.
 
Please feel free to test the model however you want. The current code is not fully optimized for large datasets, so we are particularly interested in how the current code works on large datasets and the speed. Also, because the beta weights are from yolov9-compact, so you will also find the detection confidence is lower than MegaDetectorV5, which can be a good thing as it is kinda more calibrated. And the model size is only 1/6 of the V5 model. From our other testers, the speed of V6 is also at least 4 times faster.
 
Happy testing and let me know if you have any questions!

**Comment by Ladanovasv** [comment]
Hi, Thanks for the code and model weights.

I try to use MegadetectorV6 and I have a problem
 LooseVersion = distutils.version.LooseVersion
AttributeError: module 'distutils' has no attribute 'version'

How can I fix it?

**Comment by zhmiao** [comment]
Closing this issue as we have just released MegaDetectorV6. Thanks for being patient!
