### ISSUE TITLE
Issue in using batch_image_detection in yolov8_base.py

### ISSUE THREAD

**Issue by ayush2725** [microsoft/CameraTraps#524]
### Search before asking

- [X] I have searched the Pytorch-Wildlife [issues](https://github.com/microsoft/CameraTraps/issues) and found no similar bug report.

### Bug

I'm using RTX3090 as my GPU with a lot of available space to get detections on 5,000 images, but after sometime, I just get an exception stating that too many files are open. I've attached an image of the error for your reference.

![image](https://github.com/user-attachments/assets/e904e516-b1cd-4bea-af35-fc377584f18e)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by danielaruizl1** [comment]
Hi @ayush2725! thank you for reporting the issue. Upon review, we believe the error was due to a missing data loader in the function. We have addressed this issue and made the necessary corrections in the latest version of the code. Please update to the most recent version and let us know if this resolves the error on your end.
